include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_types_on_closure_parameters: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
